
const $=id=>document.getElementById(id);let state={},selected=null,busy=false;
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>x==null?'—':Number(x).toLocaleString('en-US',{maximumFractionDigits:4});
// Translate display metadata, including snapshots created before the UI migration.
const english=x=>String(x??'').replace(/\u524d\u6bb5\uff0fIDDQ/g,'Initial / IDDQ').replace(/\u7b49\u5f85\u8cc7\u6599/g,'Waiting for data').replace(/\u6e2c\u9805\u7d50\u679c/g,'Measurements').replace(/\u6e2c\u9805\u6578\u503c\u504f\u96e2\uff08\u8f14\u52a9\u9810\u8b66\uff09/g,'Measurement outlier (supporting signal)').replace(/\u5e73\u5747\u503c\u4e0a\u5347/g,'Mean increase').replace(/\u5e73\u5747\u503c\u4e0b\u964d/g,'Mean decrease').replace(/\u6a19\u6e96\u5dee\u4e0a\u5347/g,'Standard deviation increase').replace(/\u6a19\u6e96\u5dee\u4e0b\u964d/g,'Standard deviation decrease').replace(/\u4f4e\u826f\u7387/g,'Low yield').replace(/\u7b46\u53ef\u7528\u6a23\u672c\uff1b/g,'available samples;').replace(/\u500b\u6279\u6b21\u51fa\u73fe\u8b49\u64da\uff1b\u975e\u6a5f\u7387/g,'batches with evidence; not a probability');
const post=(path,body)=>window.dashboardAPI.post(path,body);
$('start').onclick=async()=>{try{await post('/api/replay',{wafer:Number($('wafer').value),delay:Number($('speed').value)});selected=null;$('error').textContent='';}catch(e){$('error').textContent=e.message;}};
$('pause').onclick=async()=>{try{await post('/api/pause',{paused:!state.paused});}catch(e){$('error').textContent=e.message;}};
function render(s){s={...s,stage:english(s.stage),alerts:s.alerts.map(a=>({...a,label:english(a.label),first_stage:english(a.first_stage),confidence:{...a.confidence,reason:english(a.confidence.reason)}}))};state=s;const labels={anomaly:'Anomaly detected',warning:'Die signal',normal:'No anomaly detected',insufficient_data:'Insufficient data'};$('status').textContent=s.predicted_label??'Collecting data';$('status').className='value '+(s.status==='anomaly'?'bad':s.status==='normal'?'status':'warn');$('identity').textContent=s.wafer?`${s.lot} / W${s.wafer}`:'Not started';$('mode').textContent=s.mode==='live'?'Live stream':'Replay';$('completed').textContent=`${s.completed} / ${s.total_devices??'—'}`;$('batch').textContent=`Batch ${s.batch} · Received ${s.measurements_received.toLocaleString('en-US')} values`;$('yield').textContent=s.yield==null?'—':(s.yield*100).toFixed(1)+'%';$('count').textContent=s.formal_alert_count;$('formal-labels').textContent=(s.predicted_labels||[]).join(' / ')||'Insufficient data';$('warning-count').textContent=`Supporting die signals ${s.auxiliary_warning_count} events (excluded from classification)`;$('stage').textContent=s.ended?'Wafer complete':s.stage;$('action').textContent=s.alerts.some(a=>a.recommended_action==='review_pause')?'Review before pausing':s.alerts.length?'Signal detected; monitor':'Collecting data';$('progress').style.width=(s.total_devices?100*s.completed/s.total_devices:0)+'%';$('pause').disabled=!s.running;$('pause').textContent=s.paused?'Resume replay':'Pause replay';const firstPopulation=s.alerts.find(a=>a.scope==='population');$('potential').textContent=firstPopulation?`${firstPopulation.potential_unstarted_devices??'—'} dies`:'—';$('error').textContent=s.error||'';
const stages=['Initial / IDDQ',...Array.from({length:6},(_,i)=>`sensor${i+1} + subflow${i+1}`)];$('stages').innerHTML=stages.map(t=>`<span class="${t===s.stage?'active':''}">${t}</span>`).join('');
const total=Math.max(20,...s.timeline.map(p=>p.batch)), xx=b=>40+(b-1)/(total-1)*640, yy=y=>145-y*120;let chart='';for(const y of [0,.5,.8,1])chart+=`<line x1="40" x2="685" y1="${yy(y)}" y2="${yy(y)}" stroke="${y===.8?'var(--amber)':'var(--line)'}" stroke-dasharray="4 4"/><text x="0" y="${yy(y)+4}" fill="var(--muted)" font-size="11">${y*100}%</text>`;chart+=`<polyline fill="none" stroke="var(--green)" stroke-width="3" points="${s.timeline.map(p=>xx(p.batch)+','+yy(p.yield)).join(' ')}"/><text x="40" y="170" fill="var(--muted)" font-size="11">Batch 1</text><text x="625" y="170" fill="var(--muted)" font-size="11">Batch ${total}</text>`;$('chart').innerHTML=chart;
if(!s.alerts.some(a=>a.id===selected))selected=s.alerts.find(a=>a.formal_label)?.id??s.alerts[0]?.id??null;$('empty').hidden=!!s.alerts.length;
$('alerts').innerHTML=s.alerts.map(a=>{const devices=a.devices.slice(0,6).map(d=>d.pid==null?d.key:'PID '+d.pid).join(', ')+(a.devices.length>6?` … Total ${a.devices.length} dies`:'');return `<tr class="selectable ${selected===a.id?'selected':''}" data-id="${a.id}"><td>${esc(a.label)}<br><span class="sub">${esc(a.formal_label||'Supporting signal, not a class label')}</span></td><td>Batch ${a.first_batch}<br><span class="sub">${esc(a.first_stage)}</span></td><td>${esc(devices)}</td><td><span class="pill">${{low:'Low',medium:'Medium',high:'High'}[a.confidence.level]}</span></td><td>${a.recommended_action==='review_pause'?'Review pause':'Signal'}</td></tr>`;}).join('');for(const row of $('alerts').querySelectorAll('tr'))row.onclick=()=>{selected=Number(row.dataset.id);render(state);};
const a=s.alerts.find(a=>a.id===selected);$('evidence-title').textContent=a?`/ ${a.label}`:'';$('confidence').textContent=a?a.confidence.reason:'';$('evidence').innerHTML=a?a.evidence.map(e=>`<tr><td class="evidence-name">${esc(e.test||'Cumulative yield')}</td><td>${esc(e.metric)}</td><td>${fmt(e.value)}</td><td>${e.low!=null&&e.high!=null?'Outside  ['+fmt(e.low)+', '+fmt(e.high)+']':e.low!=null?'Below  '+fmt(e.low):'Above  '+fmt(e.high)}${e.metric==='cumulative_yield'?' (yield and its upper bound below 80%)':''}</td><td>${e.sample_count}</td></tr>`).join(''):'';
$('status').textContent=s.predicted_label??'Collecting data';
const classificationCaption=document.querySelector('#hero-status > .sub');
if(classificationCaption)classificationCaption.textContent=s.ended?'Wafer class':'Wafer class · Provisional';
$('formal-labels').textContent=s.predicted_label??'Collecting data';
$('action').textContent=s.predicted_label??'Collecting data';
$('model').textContent='Seven-class model · Updates after 16 completed dies · Trained on all 24 wafers; replay is not independent validation.';
window.renderVisuals(s,selected);
}
async function poll(){if(busy)return;busy=true;try{render(await window.dashboardAPI.get('/api/state?test='+(window.vizTest||0)));}catch(e){$('error').textContent='Connection lost: '+e.message;}finally{busy=false;}}
async function init(){try{const c=await window.dashboardAPI.get('/api/catalog');if(c.live_only){for(const id of ['wafer','speed','start','pause']){$(id).hidden=true;document.querySelector('label[for="'+id+'"]')?.setAttribute('hidden','');}}$('wafer').innerHTML=c.wafers.map(w=>`<option value="${w.wafer}">W${String(w.wafer).padStart(2,'0')} · ${{train_normal:'Normal training',validation_normal:'Normal validation',validation_anomaly:'Anomaly validation'}[w.split]}</option>`).join('');$('wafer').value='14';$('model').textContent=`${c.model.model} · ${c.model.training_devices} training devices · ${c.model.measurement_count} Tests · 16-die rolling window. Validation labels are not used for inference.`;const e=await window.dashboardAPI.get('/api/evaluation');$('evaluation').textContent=e.selected ? `${e.selected} ? LOO ${e.models[e.selected].correct}/${e.models[e.selected].total} ? Development CV; five singleton classes. Replay uses all 24 training wafers.` : '';await poll();setInterval(poll,300);}catch(e){$('error').textContent=e.message;}}init();
