(()=>{const $=id=>document.getElementById(id),esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),f=(v,n=3)=>v==null?'—':Number(v).toFixed(n),valid=v=>v!=null&&Number.isFinite(v);
let packet=null,sensor=0,chosen=null,run=new URLSearchParams(location.search).get('run')||'',busy=false;
function theme(){const dark=localStorage.getItem('wafer-watch-theme')==='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('theme').textContent=dark?'Light':'Dark';}theme();$('theme').onclick=()=>{localStorage.setItem('wafer-watch-theme',document.documentElement.dataset.theme==='dark'?'light':'dark');theme();render();};
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const error=(d,i)=>valid(d.pred[i])&&valid(d.actual[i])?d.pred[i]-d.actual[i]:null;
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
function render(){if(!packet)return;const s=packet.scene2,ds=s.devices||[];
$('identity').textContent=`${packet.tester} · Wafer ${s.wafer||'—'} · Batch ${s.batch}`;
$('error').textContent=(s.errors||[]).join('\n');const i=sensor;
$('sensors').innerHTML=Array.from({length:6},(_,j)=>`<button data-sensor="${j}" class="${j===i?'on':''}">sensor${j+1}</button>`).join('');for(const el of $('sensors').children)el.onclick=()=>{sensor=+el.dataset.sensor;render();};
const pairs=ds.filter(d=>error(d,i)!=null),errs=pairs.map(d=>error(d,i));
$('tiles').innerHTML=[['Measured pairs',pairs.length],['MAE °C',f(mean(errs.map(Math.abs)))],['Max error °C',f(errs.length?Math.max(...errs.map(Math.abs)):null)]].map(([k,v])=>`<div class="tile"><span class="muted">${k}</span><b>${v}</b></div>`).join('');
const known=ds.filter(d=>valid(d.x)&&valid(d.y)),xs=known.map(d=>d.x),ys=known.map(d=>d.y),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),step=Math.min(20,150/Math.max(1,xmax-xmin+1,ymax-ymin+1)),xx=x=>100+(x-(xmin+xmax)/2)*step,yy=y=>95-(y-(ymin+ymax)/2)*step;
$('maps').innerHTML=Array.from({length:6},(_,j)=>{const vals=known.map(d=>d[$('layer').value]?.[j]).filter(valid),lo=Math.min(...vals),hi=Math.max(...vals),scale=Math.max(.01,+$('scale').value||.3);return `<div class="mapcell ${i===j?'on':''}" data-sensor="${j}"><h3>sensor${j+1}</h3><svg viewBox="0 0 200 190"><circle cx="100" cy="95" r="86" fill="none" stroke="${css('--border')}"/>`+known.map(d=>{const e=error(d,j),v=$('layer').value==='error'?e:d[$('layer').value][j];const color=!valid(v)?css('--border'):$('layer').value==='error'?(v<0?css('--good'):css('--violet')):`hsl(${220-220*(v-lo)/Math.max(hi-lo,.001)} 65% 55%)`;return `<rect data-key="${esc(d.key)}" tabindex="0" role="button" aria-label="Die ${esc(d.pid??d.key)} sensor ${j+1}" x="${xx(d.x)-step*.4}" y="${yy(d.y)-step*.4}" width="${step*.8}" height="${step*.8}" rx="2" fill="${color}" fill-opacity="${valid(v)&&$('layer').value==='error'?.2+.8*Math.min(1,Math.abs(v)/scale):1}" stroke="${chosen===d.key?css('--text'):'none'}"><title>PID ${esc(d.pid)} · Site ${d.site} · ${f(v)} °C</title></rect>`;}).join('')+(!known.length?'<text x="40" y="95">Waiting for coordinates</text>':'')+'</svg></div>';}).join('');
for(const map of $('maps').children){map.onclick=e=>{sensor=+map.dataset.sensor;if(e.target.dataset.key)chosen=e.target.dataset.key;render();};map.onkeydown=e=>{if(e.key==='Enter'&&e.target.dataset.key){chosen=e.target.dataset.key;render();}};}
const d=ds.find(x=>x.key===chosen);$('die-title').textContent=d?`PID ${d.pid??'pending'} · Site ${d.site} · (${d.x??'—'}, ${d.y??'—'})`:'Select a die';$('die-detail').innerHTML=d?'<table><tr><th>Sensor</th><th>Predicted</th><th>Measured</th><th>Error °C</th></tr>'+Array.from({length:6},(_,j)=>`<tr><td>sensor${j+1}</td><td>${f(d.pred[j])}</td><td>${f(d.actual[j])}</td><td>${f(error(d,j))}</td></tr>`).join('')+'</table>':'';
$('records').innerHTML=ds.map(d=>`<tr data-key="${esc(d.key)}" class="${chosen===d.key?'selected':''}"><td>${esc(d.pid??'pending')} / ${d.site}</td><td>${f(d.pred[i])}</td><td>${f(d.actual[i])}</td><td>${f(error(d,i))}</td></tr>`).join('');for(const row of $('records').children)row.onclick=()=>{chosen=row.dataset.key;render();};
$('live').innerHTML=ds.filter(d=>!d.completed).map(d=>`<tr><td>${d.site}</td><td>${f(d.pred[i])}</td><td>${f(d.actual[i])}</td><td>${d.missing[i]??'—'}</td></tr>`).join('')||'<tr><td colspan="4">No active touchdown</td></tr>';
scatter(pairs,i);trend(ds,i);
}
function scatter(ds,i){const values=ds.flatMap(d=>[d.pred[i],d.actual[i]]),lo=Math.min(...values)-.05,hi=Math.max(...values)+.05,xy=v=>35+250*(v-lo)/(hi-lo);$('scatter').innerHTML=ds.length?`<path d="M35 205L285 205M35 205L35 25M35 205L285 25" stroke="${css('--border')}" fill="none"/><text x="45" y="230">Measured °C (${f(lo,2)} – ${f(hi,2)})</text>`+ds.map(d=>`<circle cx="${xy(d.actual[i])}" cy="${205-(xy(d.pred[i])-35)*.72}" r="3" fill="${css('--blue')}"><title>PID ${esc(d.pid)}: ${f(d.pred[i])} / ${f(d.actual[i])}</title></circle>`).join(''):'<text x="45" y="110">Waiting for measured pairs</text>';}
function trend(ds,i){let n=0,sum=0,raw=0,rn=0;const pts=[];for(const d of ds){const e=error(d,i);if(e==null)continue;n++;sum+=Math.abs(e);if(valid(d.raw[i])){raw+=Math.abs(d.raw[i]-d.actual[i]);rn++;}pts.push([sum/n,rn?raw/rn:null]);}const max=Math.max(.001,...pts.flat().filter(valid));const line=k=>pts.map((p,j)=>p[k]==null?'':`${35+250*j/Math.max(1,pts.length-1)},${205-180*p[k]/max}`).filter(Boolean).join(' ');$('trend').innerHTML=pts.length?`<text x="35" y="18">${f(max)} °C</text><text x="35" y="232">Measured pairs: ${pts.length}</text><polyline points="${line(0)}" stroke="${css('--blue')}" fill="none" stroke-width="2"/><polyline points="${line(1)}" stroke="#eb6834" fill="none" stroke-width="2"/>`:'<text x="45" y="110">Waiting for measured pairs</text>';}
async function poll(){if(busy)return;busy=true;try{const streams=await(await fetch('/api/streams')).json();const selected=$('source').value;$('source').innerHTML=streams.streams.map(s=>`<option value="${esc(s.run_id)}">${esc(s.tester)} · ${new Date(s.received_at*1000).toLocaleString('en-US')}</option>`).join('');if(run)$('source').value=run;else if(selected)$('source').value=selected;const response=await fetch('/api/temperature'+(run?'?run='+encodeURIComponent(run):''));if(!response.ok)throw Error('Waiting for Edge temperature data');const next=await response.json();if(packet?.run_id!==next.run_id||packet?.scene2.wafer!==next.scene2.wafer)chosen=null;packet=next;if(!run)$('source').value=next.run_id;const age=Math.max(next.age_seconds,(Date.now()/1000-next.received_at));$('connection').textContent=age>10?`Stale · last received ${Math.floor(age)}s ago`:'Connected · '+new Date(next.received_at*1000).toLocaleTimeString('en-US');render();}catch(e){$('connection').textContent=e.message;}finally{busy=false;}}
$('source').onchange=()=>{run=$('source').value;chosen=null;poll();};$('layer').onchange=render;$('scale').oninput=render;$('download').onclick=()=>{if(!packet)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(packet,null,2)],{type:'application/json'}));a.download='temperature-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};poll();setInterval(poll,1000);
})();
